name: Run Make to build distributions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: 
        go-version: '^1.22.0'

    - name: Validate environment
      run: go version

    - name: Test go lang (will remove)
      run: make build

    - name: Make all the go versions
      run: make all
